[package]
name = "artifacts-cli"
version = "0.1.0"
edition = "2024"
autobins = false

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
which = "6"
log = { version = "0.4", features = ["std", "serde"] }
crossterm = "0.27"

[dev-dependencies]
insta-cmd = "0.6"
insta = { version ="1.43.1" , features = ["filters"]}
serial_test = "3"

# Single binary target
[[bin]]
name = "artifacts"
path = "src/bin/artifacts.rs"
test = false
