[package]
name = "artifacts-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
which = "6"
log = { version = "0.4", features = ["std", "serde"] }

[dev-dependencies]
insta-cmd = "0.6"
insta = { version ="1.43.1" , features = ["filters"]}
serial_test = "3"

# Disable test harness for binaries so `cargo test` only runs real tests in tests/
[[bin]]
name = "artifacts-cli"
path = "src/bin/artifacts_cli.rs"
test = false

[[bin]]
name = "artifacts-tui"
path = "src/bin/artifacts_tui.rs"
test = false

